In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [7]:
# Load item dataset
item_data = pd.read_csv('./data/article.csv')

print(item_data.head())

title  sports  cooking  books  \
0                     How to Train for a Marathon    0.80     0.05   0.05   
1              The Best Recipes for a Cozy Winter    0.05     0.80   0.05   
2                        The Top 10 Books of 2023    0.05     0.05   0.80   
3  The Oscars 2023: Predictions and Controversies    0.05     0.05   0.05   
4  The Rise of Indie Games in the Gaming Industry    0.05     0.05   0.05   

   cinema  gaming  
0    0.05    0.05  
1    0.05    0.05  
2    0.05    0.05  
3    0.80    0.05  
4    0.05    0.80

In [10]:
#check item_data data type
print(item_data.dtypes)
print(item_data.shape)

title       object
sports     float64
cooking    float64
books      float64
cinema     float64
gaming     float64
dtype: object
(49, 6)


In [16]:
#create user_data dummy dataset
rng = np.random.default_rng(seed=42)
user_data = pd.DataFrame(rng.random((49,5)), columns=['sports', 'cooking', 'books', 'cinema', 'gaming'])
print(user_data.head())
print(user_data.dtypes)
print(user_data.shape)


     sports   cooking     books    cinema    gaming
0  0.773956  0.438878  0.858598  0.697368  0.094177
1  0.975622  0.761140  0.786064  0.128114  0.450386
2  0.370798  0.926765  0.643865  0.822762  0.443414
3  0.227239  0.554585  0.063817  0.827631  0.631664
4  0.758088  0.354526  0.970698  0.893121  0.778383
sports     float64
cooking    float64
books      float64
cinema     float64
gaming     float64
dtype: object
(49, 5)


In [18]:
#convert item features to numpy array
item_features = item_data[['sports', 'cooking', 'books', 'cinema', 'gaming']].values.astype(np.float32)
print(item_features[:5])
print(item_features.shape)

[[0.8  0.05 0.05 0.05 0.05]
 [0.05 0.8  0.05 0.05 0.05]
 [0.05 0.05 0.8  0.05 0.05]
 [0.05 0.05 0.05 0.8  0.05]
 [0.05 0.05 0.05 0.05 0.8 ]]
(49, 5)


In [20]:
#convert item features to numpy array
user_features = user_data[['sports', 'cooking', 'books', 'cinema', 'gaming']].values.astype(np.float32)
print(user_features[:5])
print(user_features.shape)

[[0.77395606 0.43887845 0.85859793 0.697368   0.09417735]
 [0.97562236 0.7611397  0.7860643  0.12811363 0.45038593]
 [0.37079802 0.92676497 0.6438651  0.8227616  0.4434142 ]
 [0.22723871 0.5545848  0.06381726 0.8276312  0.6316644 ]
 [0.75808775 0.35452595 0.970698   0.8931211  0.7783835 ]]
(49, 5)


In [8]:
# Define the TensorFlow model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(5,)),
    tf.keras.layers.Dense(1, activation='linear')
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

In [9]:
# Train the model
model.fit(item_features, user_profile, epochs=10)

Epoch 1/10
2/2 [==============================] - 1s 3ms/step - loss: 0.0725
Epoch 2/10
2/2 [==============================] - 0s 0s/step - loss: 0.0703
Epoch 3/10
2/2 [==============================] - 0s 3ms/step - loss: 0.0682
Epoch 4/10
2/2 [==============================] - 0s 5ms/step - loss: 0.0666
Epoch 5/10
2/2 [==============================] - 0s 6ms/step - loss: 0.0647
Epoch 6/10
2/2 [==============================] - 0s 611us/step - loss: 0.0630
Epoch 7/10
2/2 [==============================] - 0s 0s/step - loss: 0.0613
Epoch 8/10
2/2 [==============================] - 0s 4ms/step - loss: 0.0599
Epoch 9/10
2/2 [==============================] - 0s 4ms/step - loss: 0.0585
Epoch 10/10
2/2 [==============================] - 0s 7ms/step - loss: 0.0572


In [10]:
# Predict item ratings using the trained model
item_data['predicted_rating'] = model.predict(item_features)

# Sort the items based on predicted ratings in descending order
item_data = item_data.sort_values(by='predicted_rating', ascending=False)

# Get the top-k recommendations
top_k = 5
recommendations = item_data.head(top_k)['title']

2/2 [==============================] - 0s 0s/step


In [11]:
# Print the recommendations
print("Top", top_k, "recommendations for the user:")
print(recommendations)

Top 5 recommendations for the user:
18     The Best Sports Games for Mobile Devices in 2023
28    Marvel vs DC: Which Cinematic Universe is Better?
36                       How to Read More Books in 2023
27             How to Write a Bestselling Novel in 2023
15          The Most Anticipated Fantasy Novels of 2023
Name: title, dtype: object
